/*
 * generated by Xtext
 */
package hu.bme.mit.kk.dsl.ui.contentassist

import hu.bme.mit.kk.dsl.ui.contentassist.AbstractLanguageProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class LanguageProposalProvider extends AbstractLanguageProposalProvider {
}
