/*
 * generated by Xtext
 */
package hu.bme.mit.kk.dsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import hu.bme.mit.kk.dsl.services.LanguageGrammarAccess;

public class LanguageParser extends AbstractContentAssistParser {
	
	@Inject
	private LanguageGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected hu.bme.mit.kk.dsl.ui.contentassist.antlr.internal.InternalLanguageParser createParser() {
		hu.bme.mit.kk.dsl.ui.contentassist.antlr.internal.InternalLanguageParser result = new hu.bme.mit.kk.dsl.ui.contentassist.antlr.internal.InternalLanguageParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getNegationableAccess().getAlternatives_1(), "rule__Negationable__Alternatives_1");
					put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getModelAccess().getGroup_1(), "rule__Model__Group_1__0");
					put(grammarAccess.getModelAccess().getGroup_1_0(), "rule__Model__Group_1_0__0");
					put(grammarAccess.getStatementAccess().getGroup(), "rule__Statement__Group__0");
					put(grammarAccess.getIffAccess().getGroup(), "rule__Iff__Group__0");
					put(grammarAccess.getIffAccess().getGroup_1(), "rule__Iff__Group_1__0");
					put(grammarAccess.getOrAccess().getGroup(), "rule__Or__Group__0");
					put(grammarAccess.getOrAccess().getGroup_1(), "rule__Or__Group_1__0");
					put(grammarAccess.getAndAccess().getGroup(), "rule__And__Group__0");
					put(grammarAccess.getAndAccess().getGroup_1(), "rule__And__Group_1__0");
					put(grammarAccess.getNegationableAccess().getGroup(), "rule__Negationable__Group__0");
					put(grammarAccess.getNegationableAccess().getGroup_1_0(), "rule__Negationable__Group_1_0__0");
					put(grammarAccess.getPrimaryAccess().getGroup_1(), "rule__Primary__Group_1__0");
					put(grammarAccess.getKnightReferenceAccess().getGroup(), "rule__KnightReference__Group__0");
					put(grammarAccess.getKnaveReferenceAccess().getGroup(), "rule__KnaveReference__Group__0");
					put(grammarAccess.getModelAccess().getPeopleAssignment_0(), "rule__Model__PeopleAssignment_0");
					put(grammarAccess.getModelAccess().getPeopleAssignment_1_0_1(), "rule__Model__PeopleAssignment_1_0_1");
					put(grammarAccess.getModelAccess().getPeopleAssignment_1_2(), "rule__Model__PeopleAssignment_1_2");
					put(grammarAccess.getModelAccess().getStatementsAssignment_3(), "rule__Model__StatementsAssignment_3");
					put(grammarAccess.getPersonAccess().getNameAssignment(), "rule__Person__NameAssignment");
					put(grammarAccess.getStatementAccess().getPersonAssignment_0(), "rule__Statement__PersonAssignment_0");
					put(grammarAccess.getStatementAccess().getExpressionAssignment_2(), "rule__Statement__ExpressionAssignment_2");
					put(grammarAccess.getIffAccess().getRightAssignment_1_2(), "rule__Iff__RightAssignment_1_2");
					put(grammarAccess.getOrAccess().getRightAssignment_1_2(), "rule__Or__RightAssignment_1_2");
					put(grammarAccess.getAndAccess().getRightAssignment_1_2(), "rule__And__RightAssignment_1_2");
					put(grammarAccess.getNegationableAccess().getValueAssignment_1_0_2(), "rule__Negationable__ValueAssignment_1_0_2");
					put(grammarAccess.getKnightReferenceAccess().getPersonAssignment_1(), "rule__KnightReference__PersonAssignment_1");
					put(grammarAccess.getKnaveReferenceAccess().getPersonAssignment_1(), "rule__KnaveReference__PersonAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			hu.bme.mit.kk.dsl.ui.contentassist.antlr.internal.InternalLanguageParser typedParser = (hu.bme.mit.kk.dsl.ui.contentassist.antlr.internal.InternalLanguageParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public LanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
