/*
 * generated by Xtext
 */
package hu.bme.mit.kk.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LanguageRuntimeModule extends hu.bme.mit.kk.dsl.AbstractLanguageRuntimeModule {

}
